# Generated by Django 5.1.7 on 2025-03-26 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBooking', '0002_login_worker_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='desk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppBooking.desk'),
        ),
        migrations.AddField(
            model_name='worker',
            name='position',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('desk', 'reservation_time')},
        ),
    ]
